package frc.robot.autos;

public enum AutonomousModeChoices6237MR {
    BLUE_RIGHT_AUTO_MODE_1,
    RED_LEFT_AUTO_MODE_1,
    BLUE_CENTER_AUTO_MODE_1,
    RED_CENTER_AUTO_MODE_1,
    BLUE_LEFT_AUTO_MODE_1,
    RED_RIGHT_AUTO_MODE_1,
    BLUE_LEFT_DOUBLE_SPEAKER,
    RED_RIGHT_DOUBLE_SPEAKER,
    BLUE_CENTER_DOUBLE_SPEAKER,
    RED_CENTER_DOUBLE_SPEAKER,
    BLUE_RIGHT_DOUBLE_SPEAKER,
    RED_LEFT_DOUBLE_SPEAKER,
    DEBUG_ARM_AUTO,
    DEBUG_INTAKE_AUTO,
    ANGLE_PLAYGROUND,
    DEBUG_ROBOT_ROTATION,
    DEBUG_MOVEMENT,
    DEBUG_INTAKE_TO_LAUNCER,
    DEBUG_MOVE_AND_FIRE
}
