package frc.robot.autos;

public enum AutonomousModeChoices6237MR {
    EXAMPLE_AUTO,
    BLUE_RIGHT_AUTO_MODE_1,
    RED_LEFT_AUTO_MODE_1,
    BLUE_CENTER_AUTO_MODE_1,
    RED_CENTER_AUTO_MODE_1,
    BLUE_LEFT_AUTO_MODE_1,
    RED_RIGHT_AUTO_MODE_1,
    ANGLE_PLAYGROUND
}
